# Generated by Django 4.1.12 on 2023-11-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0020_room"),
    ]

    operations = [
        migrations.RemoveField(model_name="nurse", name="user",),
        migrations.AddField(
            model_name="nurse",
            name="address",
            field=models.CharField(default="abc", max_length=40),
        ),
        migrations.AddField(
            model_name="nurse",
            name="name",
            field=models.CharField(default="abc", max_length=20),
        ),
    ]
