# Generated by Django 4.1.12 on 2023-11-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0023_patient_room_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="room_num",
            field=models.CharField(default="001", max_length=10),
        ),
        migrations.AlterField(
            model_name="room",
            name="Available_beds",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="Total_beds",
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
