# Generated by Django 4.1.12 on 2023-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0024_alter_patient_room_num_alter_room_available_beds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="room_num",
            field=models.CharField(default="", max_length=10),
        ),
    ]
